- name: Init Github pages
    run: |
    npx hexo clean
    npx hexo generate
- name: Deploy
    uses: JamesIves/github-pages-deploy-action@3.1.5
    with:
    ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    BRANCH: gh-pages
    FOLDER: public
